name: WooBox
description: A new Flutter application

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_pro: 1.0.0
  http: 0.12.0+4
  crypto: ^2.0.6
  share: 0.6.3+6
  html: 0.14.0+3
  url_launcher: 5.4.2
  flutter_rating_bar: 3.0.1+1
  google_fonts: 0.3.10
  intl: 0.17.0
  percent_indicator: 2.1.1+1
  badges: 1.1.1
  firebase_core: 0.4.4+3
  firebase_analytics: 5.0.11
  firebase_crashlytics: 0.1.3+3
  firebase_auth: ^0.15.5+2
  package_info: 0.4.0+16
  expandable: 4.1.2
  provider: 4.0.4
  flutter_swiper: 1.1.6
  google_sign_in: 4.3.0
  flutter_facebook_login: 3.0.0
  geolocator: 5.3.0
  geocoder: 0.2.1
  nb_utils: 3.0.9+5
  flutter_slidable: 0.5.4
  image_picker: 0.6.4
  flutter_vector_icons: 0.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/flags/
    - lang/en.json
    - lang/fr.json
    - lang/es.json
    - lang/af.json
    - lang/de.json
    - lang/id.json
    - lang/pt.json
    - lang/tr.json
    - lang/hi.json
  fonts:
    - family: SocialIcons
      fonts:
        - asset: assets/SocialIcons.ttf